name: Validate Kubernetes Manifests

on: [push, pull_request]

jobs:
  kubeconform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Kubeconform
        run: |
          wget https://github.com/yannh/kubeconform/releases/download/v0.7.0/kubeconform-linux-amd64.tar.gz
          tar -C /usr/local/bin/ -xzf  kubeconform-linux-amd64.tar.gz
          rm kubeconform-linux-amd64.tar.gz

      - name: Validate manifests
        run: |
          RESULT=$(find ./k8s-manifests -name "*.yaml" -print0 | xargs -0 kubeconform -strict -summary || echo "FAILED")
          echo "KUBECONFORM_RESULT=${RESULT}" >> $GITHUB_ENV
          
      - name: Send Slack Notification
        if: always()
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_TOKEN }}
          webhook-type: incoming-webhoo
          message: "Результат проверки: ${{ env.KUBECONFORM_RESULT }}"

        
