name: Validate Kubernetes Manifests

on: [push, pull_request]

jobs:
  kubeconform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Kubeconform
        run: |
          wget https://github.com/yannh/kubeconform/releases/download/v0.7.0/kubeconform-linux-amd64.tar.gz
          tar -C /usr/local/bin/ -xzf  kubeconform-linux-amd64.tar.gz
          rm kubeconform-linux-amd64.tar.gz
          kubeconform -v

      - name: Validate manifests
        run: |
          find "./k8s-manifests" -name "*.yaml" -print0 | xargs -0 kubeconform -strict -summary

        
